-- Create table services
CREATE TABLE IF NOT EXISTS services (
    service_id SERIAL PRIMARY KEY,
    host_id INTEGER NOT NULL,
    service_name TEXT NOT NULL,
    street_address TEXT NOT NULL,
    city TEXT NOT NULL,
    state TEXT NOT NULL,
    zip_code TEXT NOT NULL,
    phone_number TEXT NOT NULL,
    is_open_mo INTEGER NOT NULL DEFAULT 0,
    open_time_mo TEXT NOT NULL,
    close_time_mo TEXT NOT NULL,
    is_open_tu INTEGER NOT NULL DEFAULT 0,
    open_time_tu TEXT NOT NULL,
    close_time_tu TEXT NOT NULL,
    is_open_we INTEGER NOT NULL DEFAULT 0,
    open_time_we TEXT NOT NULL,
    close_time_we TEXT NOT NULL,
    is_open_th INTEGER NOT NULL DEFAULT 0,
    open_time_th TEXT NOT NULL,
    close_time_th TEXT NOT NULL,
    is_open_fr INTEGER NOT NULL DEFAULT 0,
    open_time_fr TEXT NOT NULL,
    close_time_fr TEXT NOT NULL,
    is_open_sa INTEGER NOT NULL DEFAULT 0,
    open_time_sa TEXT NOT NULL,
    close_time_sa TEXT NOT NULL,
    is_open_su INTEGER NOT NULL DEFAULT 0,
    open_time_su TEXT NOT NULL,
    close_time_su TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT (now() at time zone 'utc'),
    updated_at TIMESTAMP NOT NULL DEFAULT (now() at time zone 'utc'),
    UNIQUE (phone_number),
    FOREIGN KEY (host_id) REFERENCES users(user_id) ON DELETE CASCADE
);